### ISSUE TITLE
SqlBuilder: SELECT DISTINCT isn't first

### ISSUE THREAD

**Issue by CZechBoY** [nette/database#98]
Hi,
the syntax of SELECT DISTINCT (for MySQL) is 
`
SELECT
    [ALL | DISTINCT | DISTINCTROW ]
      [HIGH_PRIORITY]
      [STRAIGHT_JOIN]
      [SQL_SMALL_RESULT] [SQL_BIG_RESULT] [SQL_BUFFER_RESULT]
      [SQL_CACHE | SQL_NO_CACHE] [SQL_CALC_FOUND_ROWS]
    select_expr [, select_expr ...]
`
Consider this code:
```php
$selection = $db->table('table');
$selection->select('col2');
$selection->select('DISTINCT col1');
```
then the `DISTINCT col2` is on 2nd place.

**Comment by dg** [comment]
`$selection->select('DISTINCT col1');` seems like hack, better is `$selection->select('col1')->group('col1');`

**Comment by CZechBoY** [comment]
You didn't get my problem.

Code:
```php
$selection = $this->db->table('test')
                                   ->select('col1');
$selection->select('DISTINCT col2'); // this call is after another ->select
```
and generated sql:
```sql
SELECT `col1`, DISTINCT `col2` 
FROM `test`
```
which escalates to syntax error ``SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DISTINCT `col2` FROM `test`' at line 1``

**Comment by dg** [comment]
I understand that.

**Comment by jakubskrz** [comment]
I don't think this is issue, DISTINCT isn't column operator, it affects whole SELECT statement.

Let's have this dataset:

val1 | val2
------|-------
a | a
a | b
a | c
b | a
b | b
b | c

Than query `SELECT DISTINCT val1, val2 FROM dataset` returns **all rows**, because all combination of val1 and val2 values are unique:
_(And query `SELECT DISTINCT val2, val1 FROM dataset` returns exactly same data.)_

While query `SELECT DISTINCT val1 FROM dataset` returns only two rows: **a** and **b**. And `SELECT DISTINCT val2 FROM dataset` returns values **a**, **b** and **c**.

So, if you need to select all unique values from column val2, you have to select only that column or use `GROUP BY`.
